# -*- coding: utf-8 -*-
"""Copy of Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcD8FjjwKMrZ6AasaiDgmkXamMGYc55T
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Consumer_Shopping_Trends_2026 (6).csv")

df.head()

import matplotlib.pyplot as plt
plt.hist(df['age'], bins=10)

plt.title("age Distribution")
plt.xlabel("age")
plt.ylabel("Frequency")
plt.show()

import matplotlib.pyplot as plt
plt.scatter(df['age'], df['product_availability_online'])

plt.title("age vs product_availability_online")
plt.xlabel("age")
plt.ylabel("product_availability_online (1=In Stock, 0=Out of Stock)")
plt.show()

df['product_availability_online'].value_counts().plot(kind='pie', autopct='%1.1f%%')

plt.title("product_availability_online")
plt.ylabel("")
plt.show()

df.columns = df.columns.str.strip()


corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True)

plt.title("Correlation Heatmap")
plt.show()

plt.boxplot(df['product_availability_online'])

plt.title("Boxplot of Purchase Amount")
plt.ylabel("product_availability_online")
plt.show()

